import 'dart:math' as math;

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import 'package:lucide_icons/lucide_icons.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:uuid/uuid.dart';

import '../../../../core/design_system/design_system.dart';
import '../../../tickets/domain/entities/ticket.dart';
import '../../../tickets/presentation/providers/ticket_provider.dart';
import '../../../customers/presentation/providers/customer_provider.dart';
import '../../../customers/domain/entities/customer.dart';
import '../../../auth/presentation/providers/auth_provider.dart';

class CreateTicketDialog extends ConsumerStatefulWidget {
  final bool isSupport;

  const CreateTicketDialog({super.key, this.isSupport = false});

  @override
  ConsumerState<CreateTicketDialog> createState() => _CreateTicketDialogState();
}

class _CreateTicketDialogState extends ConsumerState<CreateTicketDialog> {
  final _formKey = GlobalKey<FormState>();
  final _subjectController = TextEditingController();
  final _newCustomerNameController = TextEditingController();
  final _newCustomerPhoneController = TextEditingController();
  TextEditingController? _customerFieldController;
  String? _pendingCustomerName;

  static const _uuid = Uuid();

  String _priority = 'Medium';
  String _category = 'Technical';
  String? _selectedCustomerId;
  bool _isSubmitting = false;
  bool _showQuickCustomerForm = false;

  final _priorities = ['Low', 'Medium', 'High', 'Urgent'];
  final _categories = [
    'Technical',
    'Billing',
    'General',
    'Hardware',
    'Software',
  ];

  @override
  void dispose() {
    _subjectController.dispose();
    _newCustomerNameController.dispose();
    _newCustomerPhoneController.dispose();
    _customerFieldController = null;
    super.dispose();
  }

  InputDecoration _inputDecoration({
    String? hint,
    String? label,
    Widget? prefixIcon,
    Widget? suffixIcon,
  }) {
    return InputDecoration(
      labelText: label,
      hintText: hint,
      prefixIcon: prefixIcon,
      suffixIcon: suffixIcon,
      hintStyle: TextStyle(color: AppColors.slate400),
      border: _outlineBorder(AppColors.slate300),
      enabledBorder: _outlineBorder(AppColors.slate300),
      focusedBorder: _outlineBorder(AppColors.primary),
      contentPadding: const EdgeInsets.symmetric(horizontal: 12, vertical: 12),
    );
  }

  OutlineInputBorder _outlineBorder(Color color) {
    return OutlineInputBorder(
      borderRadius: BorderRadius.circular(8),
      borderSide: BorderSide(color: color, width: 1.2),
    );
  }

  Future<void> _createTicket({bool assignToSelf = false}) async {
    if (!_formKey.currentState!.validate()) {
      return;
    }

    if (!_showQuickCustomerForm && (_selectedCustomerId == null || _selectedCustomerId!.isEmpty)) {
      return;
    }

    setState(() => _isSubmitting = true);

    bool success = false;

    try {
      final currentUser = ref.read(authProvider);

      String? customerId = _selectedCustomerId;

      if (_showQuickCustomerForm) {
        final newCustomer = await _createCustomerFromQuickForm();
        if (newCustomer == null) {
          setState(() => _isSubmitting = false);
          return;
        }
        customerId = newCustomer.id;
      }

      if (customerId == null) {
        setState(() => _isSubmitting = false);
        return;
      }

      final subject = _subjectController.text.trim();
      final ticket = Ticket(
        ticketId: '', // Will be generated by database
        customerId: customerId,
        title: subject,
        description: subject,
        status: 'New',
        priority: _priority,
        category: _category,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
        createdBy: currentUser?.id ?? '',
        assignedTo: assignToSelf ? currentUser?.id : null,
      );

      success = await ref
          .read(ticketCreatorProvider.notifier)
          .createTicket(ticket);

      if (success) {
        ref.invalidate(ticketsStreamProvider);
      }
    } catch (e) {
      // Error is handled silently - could add proper logging here if needed
      // Log.error('CreateTicketDialog _createTicket error', error: e);
    } finally {
      if (mounted) {
        setState(() => _isSubmitting = false);
      }
    }

    if (!mounted) return;

    if (success) {
      context.pop();
    }
  }

  @override
  Widget build(BuildContext context) {
    final customersAsync = ref.watch(customersListProvider);

    final screenWidth = MediaQuery.of(context).size.width;
    final dialogWidth = math.max(520.0, math.min(screenWidth - 72, 860.0));

    return Align(
      alignment: Alignment.topCenter,
      child: Padding(
        padding: const EdgeInsets.fromLTRB(24, 48, 24, 16),
        child: Material(
          elevation: 12,
          color: Colors.white,
          borderRadius: BorderRadius.circular(16),
          clipBehavior: Clip.antiAlias,
          child: ConstrainedBox(
            constraints: BoxConstraints(maxWidth: dialogWidth),
            child: Container(
              width: dialogWidth,
              padding: const EdgeInsets.symmetric(horizontal: 36, vertical: 32),
              child: Form(
                key: _formKey,
                child: SingleChildScrollView(
                  child: Column(
                    mainAxisSize: MainAxisSize.min,
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      // Header
                      Row(
                        mainAxisAlignment: MainAxisAlignment.spaceBetween,
                        children: [
                          const Text(
                            'Create New Ticket',
                            style: TextStyle(
                              fontSize: 18,
                              fontWeight: FontWeight.w600,
                              color: AppColors.slate900,
                            ),
                          ),
                          IconButton(
                            icon: const Icon(LucideIcons.x, size: 20),
                            onPressed: () => context.pop(),
                            padding: EdgeInsets.zero,
                            constraints: const BoxConstraints(),
                          ),
                        ],
                      ),
                      const SizedBox(height: 28),

                      // Customer selector
                      Row(
                        children: [
                          const Text(
                            'Customer *',
                            style: TextStyle(
                              fontWeight: FontWeight.w500,
                              fontSize: 13,
                              color: AppColors.slate900,
                            ),
                          ),
                          const SizedBox(width: 8),
                          Tooltip(
                            message:
                                _showQuickCustomerForm ? 'Back to customer search' : 'New customer',
                            child: IconButton(
                              icon: Icon(
                                _showQuickCustomerForm
                                    ? LucideIcons.search
                                    : LucideIcons.userPlus,
                                size: 18,
                              ),
                              padding: EdgeInsets.zero,
                              constraints: const BoxConstraints(),
                              onPressed: () {
                                setState(() {
                                  _showQuickCustomerForm = !_showQuickCustomerForm;
                                  _selectedCustomerId = null;
                                  _customerFieldController?.clear();
                                  _pendingCustomerName = null;
                                  _newCustomerNameController.clear();
                                  _newCustomerPhoneController.clear();
                                });
                              },
                            ),
                          ),
                        ],
                      ),
                      const SizedBox(height: 6),
                      if (!_showQuickCustomerForm)
                        customersAsync.when(
                          data: (customers) => LayoutBuilder(
                            builder: (context, constraints) => Autocomplete<Customer>(
                              displayStringForOption: (option) => option.companyName,
                              optionsBuilder: (text) {
                                if (text.text.isEmpty) {
                                  return const Iterable<Customer>.empty();
                                }
                                return customers.where((option) =>
                                    option.companyName
                                        .toLowerCase()
                                        .contains(text.text.toLowerCase()));
                              },
                              onSelected: (selection) {
                                setState(() {
                                  _selectedCustomerId = selection.id;
                                  _customerFieldController?.text = selection.companyName;
                                });
                              },
                              fieldViewBuilder:
                                  (context, controller, focusNode, onFieldSubmitted) {
                                _customerFieldController ??= controller;
                                if (_pendingCustomerName != null) {
                                  controller.text = _pendingCustomerName!;
                                  _pendingCustomerName = null;
                                }
                                return TextFormField(
                                  controller: controller,
                                  focusNode: focusNode,
                                  decoration: _inputDecoration(
                                    hint: 'Search customer...',
                                    suffixIcon: const Icon(LucideIcons.search, size: 16),
                                  ),
                                  onChanged: (value) {
                                    if (value.isEmpty) {
                                      setState(() => _selectedCustomerId = null);
                                    }
                                  },
                                  onFieldSubmitted: (_) => onFieldSubmitted(),
                                  validator: (_) {
                                    if (_showQuickCustomerForm) return null;
                                    if (_selectedCustomerId == null ||
                                        _selectedCustomerId!.isEmpty) {
                                      return 'Please select a customer from the list';
                                    }
                                    return null;
                                  },
                                );
                              },
                              optionsViewBuilder: (context, onSelected, options) {
                                final optionList = options.toList();
                                final hasResults = optionList.isNotEmpty;
                                final rows = hasResults ? optionList.length : 1;
                                final maxHeight = hasResults
                                    ? math.min(420.0, rows * 76.0)
                                    : 120.0;

                                return Align(
                                  alignment: Alignment.topLeft,
                                  child: Material(
                                    elevation: 4,
                                    borderRadius: BorderRadius.circular(8),
                                    child: SizedBox(
                                      height: maxHeight,
                                      width: constraints.maxWidth,
                                      child: hasResults
                                          ? ListView.separated(
                                              padding: EdgeInsets.zero,
                                              itemCount: optionList.length,
                                              physics: const BouncingScrollPhysics(),
                                              separatorBuilder: (_, __) =>
                                                  const Divider(height: 1, thickness: 0.5),
                                              itemBuilder: (context, index) {
                                                final option = optionList[index];
                                                return ListTile(
                                                  title: Text(option.companyName),
                                                  subtitle:
                                                      Text(option.contactPerson ?? 'No contact name'),
                                                  trailing: option.isAmcActive
                                                      ? const Chip(
                                                          label: Text('AMC Active'),
                                                          backgroundColor: AppColors.success,
                                                          labelStyle: TextStyle(
                                                            color: Colors.white,
                                                            fontSize: 11,
                                                          ),
                                                        )
                                                      : const Chip(
                                                          label: Text('AMC Expired'),
                                                          backgroundColor: AppColors.error,
                                                          labelStyle: TextStyle(
                                                            color: Colors.white,
                                                            fontSize: 11,
                                                          ),
                                                        ),
                                                  onTap: () => onSelected(option),
                                                );
                                              },
                                            )
                                          : const Center(
                                              child: Padding(
                                                padding: EdgeInsets.all(16),
                                                child: Text(
                                                  'No customers match your search',
                                                  style: TextStyle(color: AppColors.slate500),
                                                ),
                                              ),
                                            ),
                                    ),
                                  ),
                                );
                              },
                            ),
                          ),
                          loading: () => const LinearProgressIndicator(),
                          error: (_, __) => const Text('Error loading customers'),
                        ),

                      if (_showQuickCustomerForm)
                        Padding(
                          padding: const EdgeInsets.only(top: 12),
                          child: Column(
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              TextFormField(
                                controller: _newCustomerNameController,
                                decoration: _inputDecoration(
                                  label: 'Customer Name',
                                  prefixIcon: const Icon(LucideIcons.user),
                                ),
                                validator: (value) {
                                  if (!_showQuickCustomerForm) return null;
                                  if (value == null || value.trim().isEmpty) {
                                    return 'Customer name is required';
                                  }
                                  return null;
                                },
                              ),
                              const SizedBox(height: 12),
                              TextFormField(
                                controller: _newCustomerPhoneController,
                                keyboardType: TextInputType.phone,
                                decoration: _inputDecoration(
                                  label: 'Phone Number',
                                  prefixIcon: const Icon(LucideIcons.phone),
                                ),
                                validator: (value) {
                                  if (!_showQuickCustomerForm) return null;
                                  if (value == null || value.trim().isEmpty) {
                                    return 'Phone number is required';
                                  }
                                  return null;
                                },
                              ),
                              const SizedBox(height: 10),
                              Align(
                                alignment: Alignment.centerLeft,
                                child: TextButton(
                                  onPressed: () {
                                    setState(() {
                                      _showQuickCustomerForm = false;
                                      _newCustomerNameController.clear();
                                      _newCustomerPhoneController.clear();
                                    });
                                  },
                                  child: const Text('Cancel New Customer'),
                                ),
                              ),
                            ],
                          ),
                        ),

                      const SizedBox(height: 14),
                      const Text(
                        'Subject / Description *',
                        style: TextStyle(
                          fontWeight: FontWeight.w500,
                          fontSize: 13,
                          color: AppColors.slate900,
                        ),
                      ),
                      const SizedBox(height: 6),
                      TextFormField(
                        controller: _subjectController,
                        minLines: 3,
                        maxLines: 6,
                        decoration: _inputDecoration(
                          hint: 'Describe the problem...',
                        ),
                        validator: (value) {
                          if (value == null || value.trim().isEmpty) {
                            return 'Please enter a subject or description';
                          }
                          return null;
                        },
                      ),

                      const SizedBox(height: 14),
                      Row(
                        children: [
                          Expanded(
                            child: Column(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                const Text(
                                  'Priority',
                                  style: TextStyle(
                                    fontWeight: FontWeight.w500,
                                    fontSize: 13,
                                    color: AppColors.slate900,
                                  ),
                                ),
                                const SizedBox(height: 6),
                                DropdownButtonFormField<String>(
                                  initialValue: _priority,
                                  decoration: InputDecoration(
                                    border: OutlineInputBorder(
                                      borderRadius: BorderRadius.circular(6),
                                      borderSide: const BorderSide(color: AppColors.slate200),
                                    ),
                                    enabledBorder: OutlineInputBorder(
                                      borderRadius: BorderRadius.circular(6),
                                      borderSide: const BorderSide(color: AppColors.slate200),
                                    ),
                                    contentPadding: const EdgeInsets.symmetric(
                                      horizontal: 12,
                                      vertical: 10,
                                    ),
                                  ),
                                  items: _priorities.map((priority) {
                                    return DropdownMenuItem(
                                      value: priority,
                                      child: Text(priority),
                                    );
                                  }).toList(),
                                  onChanged: (value) {
                                    if (value != null) {
                                      setState(() => _priority = value);
                                    }
                                  },
                                ),
                              ],
                            ),
                          ),
                          const SizedBox(width: 12),
                          Expanded(
                            child: Column(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                const Text(
                                  'Category',
                                  style: TextStyle(
                                    fontWeight: FontWeight.w500,
                                    fontSize: 13,
                                    color: AppColors.slate900,
                                  ),
                                ),
                                const SizedBox(height: 6),
                                DropdownButtonFormField<String>(
                                  initialValue: _category,
                                  decoration: InputDecoration(
                                    border: OutlineInputBorder(
                                      borderRadius: BorderRadius.circular(6),
                                      borderSide: const BorderSide(color: AppColors.slate200),
                                    ),
                                    enabledBorder: OutlineInputBorder(
                                      borderRadius: BorderRadius.circular(6),
                                      borderSide: const BorderSide(color: AppColors.slate200),
                                    ),
                                    contentPadding: const EdgeInsets.symmetric(
                                      horizontal: 12,
                                      vertical: 10,
                                    ),
                                  ),
                                  items: _categories.map((category) {
                                    return DropdownMenuItem(
                                      value: category,
                                      child: Text(category),
                                    );
                                  }).toList(),
                                  onChanged: (value) {
                                    if (value != null) {
                                      setState(() => _category = value);
                                    }
                                  },
                                ),
                              ],
                            ),
                          ),
                        ],
                      ),

                      const SizedBox(height: 24),
                      Row(
                        mainAxisAlignment: MainAxisAlignment.end,
                        children: [
                          TextButton(
                            onPressed: () => context.pop(),
                            style: TextButton.styleFrom(
                              padding:
                                  const EdgeInsets.symmetric(horizontal: 20, vertical: 10),
                            ),
                            child: const Text(
                              'Cancel',
                              style: TextStyle(
                                color: AppColors.slate600,
                                fontWeight: FontWeight.w500,
                              ),
                            ),
                          ),
                          const SizedBox(width: 10),
                          FilledButton(
                            onPressed: _isSubmitting
                                ? null
                                : () => _createTicket(assignToSelf: false),
                            style: FilledButton.styleFrom(
                              backgroundColor: AppColors.primary,
                              padding: const EdgeInsets.symmetric(
                                horizontal: 20,
                                vertical: 10,
                              ),
                              shape: RoundedRectangleBorder(
                                borderRadius: BorderRadius.circular(6),
                              ),
                            ),
                            child: const Text(
                              'Push to Unclaimed',
                              style: TextStyle(
                                fontWeight: FontWeight.w500,
                                color: Colors.white,
                              ),
                            ),
                          ),
                        ],
                      ),
                    ],
                  ),
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }

  Future<Customer?> _createCustomerFromQuickForm() async {
    final name = _newCustomerNameController.text.trim();
    final phone = _newCustomerPhoneController.text.trim();

    if (name.isEmpty || phone.isEmpty) {
      return null;
    }

    try {
      final response = await Supabase.instance.client
          .from('customers')
          .insert({
            'company_name': name,
            'contact_phone': phone,
            'contact_phone_numbers': [phone],
            'api_key': _generateTempApiKey(),
          })
          .select()
          .single();

      final newCustomer = Customer.fromJson(
        Map<String, dynamic>.from(response as Map),
      );

      ref.invalidate(customersListProvider);

      if (mounted) {
        setState(() {
          _showQuickCustomerForm = false;
          _selectedCustomerId = newCustomer.id;
          _pendingCustomerName = newCustomer.companyName;
          _newCustomerNameController.clear();
          _newCustomerPhoneController.clear();
        });
      }

      return newCustomer;
    } catch (e) {
      return null;
    }
  }

  String _generateTempApiKey() {
    final raw = _uuid.v4();
    return raw.replaceAll('-', '').toUpperCase();
  }
}
